Fix wrong visibleValues in sw-select component
shopware/meteor-component-library pull request #47
Opened 2022-12-27 08:31 UTC by crisalder2806

### Issue
The current `visibleValues` computed property is using `includes` method which leads to a bug when for example, the options can be like this:
```js
const options = [
  {
    label: '100',
   value: '100'
  },
  {
    label: '1000',
   value: '1000'
  }
]
```

In the above case, `visibleValues` will result in an array of ['100', '1000'] which is not expected when you only use single select.

### Solution
Treat the value of single select and multi-select separately, and only use `includes` method when checking the value for multi-select.

2022-12-27 09:52 UTC, jleifeld commented
Changelog is missing

2022-12-27 09:52 UTC, jleifeld commented
Can you also write tests for this to make sure it don't break in the future?

2022-12-27 09:53 UTC, jleifeld commented
And you can update the version in the package.json to a new patch version so that the new package gets automatically released

2022-12-27 09:53 UTC, jleifeld requested changes
See comments

2022-12-28 08:27 UTC, crisalder2806 commented
@jleifeld Is here the correct place to write the changelog?

<img width="460" alt="image" src="https://user-images.githubusercontent.com/24885765/209782183-ae137b9a-8265-4a73-9e91-f86ef868848a.png">

2022-12-29 14:03 UTC, jleifeld commented
> @jleifeld Is here the correct place to write the changelog?
> 
> <img alt="image" width="460" src="https://user-images.githubusercontent.com/24885765/209782183-ae137b9a-8265-4a73-9e91-f86ef868848a.png">

Yeah, this is correct. And then you can also changed the Unreleased to the newly released version. You can orientate to this structure: https://github.com/shopware/admin-extension-sdk/blob/main/CHANGELOG.md

2022-12-30 08:32 UTC, crisalder2806 commented
@jleifeld I updated the PR now. Could you help me to check again? Thank you.

2023-01-02 09:52 UTC, jleifeld approved these changes

2023-01-02 10:05 UTC, jleifeld approved these changes

2023-01-02 10:37 UTC, merged